module.exports = {
    APP_NAME: 'Namma Ooru Taxi',
    companyName: 'Namma Ooru Taxi',
    companyAddress: '123, Main Street, Anytown, USA',
    companyPhone: '+1234567890',
    companyEmail: 'info@nammaoorutaxi.com',
    APP_VERSION: '1.0.0',
    APP_BUILD_NUMBER: '1',
    APP_BUILD_VERSION: '1.0.0',
    SHOW_WAIT_PRICE_INFO:false,
    DEFAULT_WAIT_TIME: 5,
    WAIT_TIME_CHARGES_PER_MINUTE: 2,
    MAX_WAIT_TIME: 60,
    PAYMENT_METHODS:"PG",
    SHOW_NEARBY_DRIVER: false,
    DRIVER_LOCATION_UPDATE_INTERVAL: 10,
    SHOW_NEARBY_DRIVER_RADIUS: 10000,
    MIN_TRIP_DISTANCE_METER: 100,
    CUSTOMER_CANCEL_PENALTY:true,
    CUSTOMER_CANCEL_PENALTY_LIMIT: 3
}
