module.exports = {
    PENDING: 'PENDING',
    SCHEDULED: 'SCHEDULED',
    MATCHED: 'MATCHED',
    ACCEPTED: 'ACCEPTED',
    PICKEDUP: 'PICKEDUP',
    DROPPED: 'DROPPED',
    PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    DIVERGED: 'DIVERGED'
}