module.exports = {
    SEDAN: 'SEDAN',
    SUV: 'SUV',
    AUTO: 'AUTO',
    HATCHBACK: 'HATCHBACK',
    BIKE: 'BIKE',
    ELECTRIC_BIKE: 'ELECTRIC_BIKE',
    ELECTRIC_SEDAN: 'ELECTRIC_SEDAN',
    ELECTRIC_SUV: 'ELECTRIC_SUV',
    ELECTRIC_AUTO: 'ELECTRIC_AUTO',
    ELECTRIC_HATCHBACK: 'ELECTRIC_HATCHBACK',
}