import { create } from 'zustand';

const useCurrentRideInfoStore = create((set) => ({
  tripId: null,
  tripStatus: 'ACCEPTED',
  rideStartLocation: null,
  rideEndLocation: null,
  stops: [],
  duration: null,
  basePrice: null,
  maxPrice: null,
  totalDistance: null,
  currentDistance: null,
  otp: null,
  estArrivalTime: null,
  paymentMethod: null,
  // Additional fields from trip data
  bookingFor: null,
  bookingForName: null,
  bookingForPhone: null,
  bookingTime: null,
  pickupTime: null,
  passangerCount: null,
  passangerId: null,
  vehicleType: null,
  publicRidesTrip: null,

  setTripId: (tripId) => set({ tripId }),
  setTripStatus: (tripStatus) => set({ tripStatus }),
  setRideStartLocation: (rideStartLocation) => set({ rideStartLocation }),
  setRideEndLocation: (rideEndLocation) => set({ rideEndLocation }),
  setStops: (stops) => set({ stops }),
  setDuration: (duration) => set({ duration }),
  setBasePrice: (basePrice) => set({ basePrice }),
  setMaxPrice: (maxPrice) => set({ maxPrice }),
  setTotalDistance: (totalDistance) => set({ totalDistance }),
  setCurrentDistance: (currentDistance) => set({ currentDistance }),
  setOtp: (otp) => set({ otp }),
  setEstArrivalTime: (estArrivalTime) => set({ estArrivalTime }),
  setPaymentMethod: (paymentMethod) => set({ paymentMethod }),

  setCurrentRideInfo: (info) => set({
    tripId: info._id || info.tripId || null,
    tripStatus: info.status || info.tripStatus || null,
    rideStartLocation: info.startLocation || info.rideStartLocation || null,
    rideEndLocation: info.endLocation || info.rideEndLocation || null,
    stops: info.stops || [],
    duration: info.estimatedDuration || info.duration || null,
    basePrice: info.minFare || info.basePrice || null,
    maxPrice: info.maxFare || info.maxPrice || null,
    totalDistance: info.distance || info.totalDistance || null,
    currentDistance: info.distance || info.currentDistance || null,
    otp: info.otp ?? null,
    estArrivalTime: info.estArrivalTime ?? null,
    paymentMethod: info.paymentMethod || null,
    // Additional fields from sample data
    bookingFor: info.bookingFor || null,
    bookingForName: info.bookingForName || null,
    bookingForPhone: info.bookingForPhone || null,
    bookingTime: info.bookingTime || null,
    pickupTime: info.pickupTime || null,
    passangerCount: info.passangerCount || null,
    passangerId: info.passangerId || null,
    vehicleType: info.vehicleType || null,
    publicRidesTrip: typeof info.publicRidesTrip === 'boolean' ? info.publicRidesTrip : null,
  }),

  setFareDetails: (fareDetails) => set({ fareDetails }),

  resetCurrentRideInfo: () => set({
    tripId: null,
    tripStatus: 'ACCEPTED',
    rideStartLocation: null,
    rideEndLocation: null,
    stops: [],
    duration: null,
    basePrice: null,
    maxPrice: null,
    totalDistance: null,
    currentDistance: null,
    otp: null,
    estArrivalTime: null,
    paymentMethod: null,
    // Reset additional fields
    bookingFor: null,
    bookingForName: null,
    bookingForPhone: null,
    bookingTime: null,
    pickupTime: null,
    passangerCount: null,
    passangerId: null,
    vehicleType: null,
    publicRidesTrip: null,
  }),
}));

export default useCurrentRideInfoStore;
