import { StyleSheet } from "react-native";
import { colors, Fonts } from "../constants/constants";
import { commonStyles } from "./commonStyles";

export const serviceStyles = StyleSheet.create({
    screen:{
      flex:1,
      backgroundColor:colors.white
    },
    container:{
      marginTop:80,
      width:'90%',
      alignSelf:'center'
    },
    serviceTypeBtn:{
      backgroundColor:colors.white,
      borderWidth:1,
      borderColor:colors.grey,
      borderRadius:8,
      flexDirection:'row',
      justifyContent:'space-between',
      paddingHorizontal:8,
      paddingVertical:8,
      marginTop:10,
      alignItems:'center'
    },
    serviceTypeBtnTxt:{
      fontFamily:Fonts.light,
      color:colors.black,
      fontSize:16
    },
    areaListcontainer:{
        width:'90%',
        alignSelf:'center'
    },
    bottomBtnContainer:{
        position:'absolute',
        bottom:20,
        zIndex:9999,
        right:20
    },
    plusBtn:{
        backgroundColor:colors.yellow,
        width:40,
        height:40,
        borderRadius:50,
        alignItems:'center',
        justifyContent:'center',
        ...commonStyles.shadow
    },
    dutyPrefernceTxt:{
        fontFamily:Fonts.regular,
        color:colors.black,
        fontSize:16
    }
  })

  export const tripStyles = StyleSheet.create({
    filterContainer:{
      width:'100%',
      alignSelf:'center',
      flexDirection:'row',
      justifyContent:'space-between',
      paddingVertical:10,
      paddingHorizontal:10
    },
    FilterBtn:{
      alignItems:'center',
      justifyContent:'center',
      paddingHorizontal:18,
      borderRightWidth:0.3,
    },
    FilterBtnTxt:{
      fontFamily:Fonts.light,
      fontSize:16
    },
    listContainer:{
      marginTop:10,
    },
    tripCard:{
      width:'90%',
      alignSelf:'center',
      backgroundColor:colors.white_light,
      paddingVertical:10,
      paddingHorizontal:5,
      borderRadius:8
    },
    detailsCard:{
      flexDirection:'row',
      justifyContent:'space-between',
      borderBottomWidth:0.3,
    },
    detailsTitle:{
      fontFamily:Fonts.light,
      fontSize:12,
      color:colors.black
    },
    detailsText:{
      fontFamily:Fonts.medium,
      fontSize:14,
      color:colors.black,
      marginTop:5
    },
    startLocationIcon:{
      position:'absolute',
      left:-12,
      top:-8
    },
    startLocation:{
      flexDirection:'row',
      borderLeftWidth:1,
      marginTop:20,
      width:'90%',
      alignSelf:'center',
      borderStyle:'dashed'
    },
    startLocationNameContainer:{
      marginLeft:18
    },
    startLocationText:{
      fontFamily:Fonts.light,
      fontSize:14,
      color:colors.grey_xxdark
    },
    startLocationName:{
      fontFamily:Fonts.regular,
      fontSize:16,
      color:colors.black
    },
    endLocation:{
      flexDirection:'row',
      width:'90%',
      alignSelf:'center',
      marginTop:5
    },
    EndLocationIcon:{
      position:'absolute',
      left:-4,
    }
  })