import {StyleSheet} from 'react-native';
import {Colors, Fonts} from '../Constants/Contants';

export const UserScreenStyles = StyleSheet.create({
    screen: {
        flex:1,
        padding:20
    },
    loginTxt:{
        fontFamily:Fonts.medium,
        color:Colors.black,
        fontSize:30
    },
    loginBg:{
        width:'90%',
        alignSelf:'center',
        alignItems:'center',
        paddingVertical:10,
        marginTop:20
    },
    inputContainer:{
        width:'100%',
        alignSelf:'center',
        marginTop:10,
    },
    input:{
        borderBottomWidth:0.4,
        height:40,
        width:'100%',
        fontFamily:Fonts.regular,
        color:Colors.black,
        fontSize:14
    },
    inputTitle:{
        fontFamily:Fonts.regular,
        color:Colors.black,
        fontSize:14
    },
    orContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        width:'70%',
        alignSelf:'center',
        marginTop:15,
    },
    lineView:{
        height:2,
        width:100,
        backgroundColor:Colors.black,
        top:2
    },
    socialBtns:{
        width:'75%',
        alignSelf:'center',
        backgroundColor:'red',
        alignItems:'center',
        marginTop:15,
        paddingVertical:10,
        borderRadius:20,
        flexDirection:'row',
        justifyContent:'space-evenly',
        paddingHorizontal:20
    },
    socialBtnTxt:{
        fontFamily:Fonts.regular,
        color:Colors.white,
    },
    useOfGmail:{
        fontFamily:Fonts.light,
        color:Colors.black,
        fontSize:12,
        width:'75%',
        textAlign:'center',
        alignSelf:'center',
        marginTop:10
    },
    bottomBtn:{
        position:'absolute',
        bottom:20,
        alignSelf:'center',
    },
    bottomTxt:{
        fontFamily:Fonts.regular,
        color:Colors.black,
        fontSize:16
    }
});
