import { StyleSheet } from "react-native";
import { Colors, Fonts } from "../../common/constants/constants";
import { height } from "../../common/utils/scalingutils";


export const RouteScreenStyles = StyleSheet.create({
    mapIconContainer: {
        alignSelf: 'flex-end',
        marginRight: 10,
        marginTop: 10,
      },
      backBtn: {
        position: 'absolute',
      },
      headerContainer: {
        backgroundColor: Colors.black,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        width: '90%',
        paddingVertical: 10,
        paddingHorizontal: 10,
        alignSelf: 'center',
      },
      stopTxt: {
        color: Colors.white,
        fontSize: 16,
        fontFamily: Fonts.medium,
        textTransform:'capitalize'
      },
      addressTxt: {
        color: '#d6d6d6',
        fontSize: 12,
        fontFamily: Fonts.medium,
      },
      detailsContainer: {
        backgroundColor: Colors.white,
        padding: 10,
        width: '100%',
        flex: 1,
      },
      durationText: {
        color: '#009205',
        fontFamily: Fonts.medium,
        fontSize: 18,
      },
      durationTxt2: {
        color: Colors.black,
        fontFamily: Fonts.regular,
        fontSize: 14,
        marginTop: 10,
      },
      passangerCountContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: Colors.pale_grey_two,
        padding: 10,
        borderRadius: 10,
      },
      countTxt: {
        color: Colors.black,
        fontFamily: Fonts.medium,
        fontSize: 16,
      },
      contentContainer: {
        flex: 1,
      },
      durationContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '96%',
        alignSelf: 'center',
        marginTop: 10,
        borderBottomWidth: 0.3,
        paddingBottom: 10,
      },
      flatListContent: {
        paddingBottom: 10,
        backgroundColor: Colors.white,
      },
      stopsItemCard: {
        width: '90%',
        alignSelf: 'center',
        backgroundColor: '#fafafa',
        padding: 10,
        borderRadius: 6,
        marginVertical: 5,
        flexDirection: 'row',
        gap: 10,
      },
      stopNameTxt: {
        fontFamily: Fonts.regular,
        fontSize: 12,
        color: '#757575',
        textTransform:'capitalize'
      },
      stopAddressTxt: {
        fontFamily: Fonts.regular,
        fontSize: 12,
        color: '#424242',
        marginVertical: 4,
      },
      stopArrivalTimeTxt: {
        fontFamily: Fonts.regular,
        fontSize: 12,
        color: '#424242',
      },
      markerIcons: {
        top: 2,
      },
      // navigationIconContainer: {
      //   width: '13%',
      //   backgroundColor: '#0080ff',
      //   aspectRatio: 1,
      //   borderRadius: 100,
      //   alignItems: 'center',
      //   justifyContent: 'center',
      //   alignSelf: 'flex-end',
      //   right: 15,
      //   marginBottom: 10,
      //   borderWidth: 1,
      //   borderColor: Colors.white,
      //   position: 'absolute',
      //   top: -height * 0.08,
      //   zIndex: 9999,
      // },
      modalView: {
        // margin: 20,
        backgroundColor: 'white',
        borderRadius: 8,
        padding: 10,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
      },
      centeredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        // backgroundColor: 'rgba(0, 0, 0, 0.5)',
      },
      noActiveRouteContainer: {
        position: 'absolute',
        bottom: 0,
        backgroundColor: Colors.white,
        width: '100%',
        alignSelf: 'center',
        padding: 10,
        height: height * 0.3,
        alignItems: 'center',
        justifyContent: 'center',
      },
      noActiveRouteTxt: {
        fontFamily: Fonts.semi_bold,
        fontSize: 22,
        color: Colors.black,
        // top: 50,
      },
      endTripBtn: {
        backgroundColor: '#ff5d5d',
        padding: 10,
        borderRadius: 8,
        width: '90%',
        alignSelf: 'center',
        marginTop: 10,
        alignItems: 'center',
      },
      endTripTxt: {
        color: Colors.white,
        fontFamily: Fonts.medium,
      },
      startNowBtn: {
        width: '90%',
        backgroundColor: '#00b74f',
        alignItems: 'center',
        paddingVertical: 10,
        borderRadius: 8,
        alignSelf: 'center',
        marginVertical: 10,
      },
      startNowTxt: {
        color: Colors.white,
        fontFamily: Fonts.regular,
        fontSize: 12,
      },
      enableNowBtn: {
        backgroundColor: Colors.white,
        padding: 5,
        borderRadius: 8,
      },
      stopsItemContainer: {
        width: '90%',
        alignSelf: 'center',
        backgroundColor: '#fafafa',
        borderRadius: 6,
        marginVertical: 5,
    },
    acceptBtn:{
      backgroundColor:Colors.green,
      padding:10,
      borderRadius:8,
      width:'40%',
      alignSelf:'center',
      alignItems:'center',
    },
    acceptBtnTxt:{
      color:Colors.white,
      fontFamily:Fonts.medium,
      fontSize:12,
    },
    endTripModalTxt:{
      fontFamily:Fonts.medium,
      fontSize:14,
      color:Colors.black,
      textAlign:'center',
      marginVertical:10,
    },
    endTripModalTxtPassanger:{
      fontFamily:Fonts.medium,
      fontSize:12,
      color:Colors.black,
    },
    reachedWaypointBtn:{
      width:'90%',
      alignItems:'center',
      backgroundColor:Colors.periwinkle,
      alignSelf:'center',
      paddingVertical:10,
      borderRadius:10,
      elevation:5,
      justifyContent:'center',
    },
    reachedWaypointBtnTxt:{
      fontFamily:Fonts.regular,
      fontSize:16,
      color:Colors.white,
      textAlign:'center',
    },
    modalViewHeaderTxt:{
      fontFamily:Fonts.regular,
      fontSize:14,
      marginBottom:10,
      textAlign:'left'
    },
    skipBtn:{
      width:'80%',
      backgroundColor:'red',
      paddingVertical:10,
      alignItems:'center',
      paddingHorizontal:10,
      borderRadius:8,
      marginBottom:10,
      elevation:2
    },
    skipBtnTxt:{
      fontFamily:Fonts.medium,
      fontSize:12,
      color:Colors.white
    },
    modalViewHeaderDetails:{
      elevation:2,
      backgroundColor:Colors.white,
      marginVertical:10,
      paddingHorizontal:10,
      borderRadius:8
    },
    watingTimeContainer:{
      width:'90%',
      // flexDirection:'row',
      alignSelf:'center',
      marginVertical:10,
      alignItems:'center',
      backgroundColor:Colors.grey_light,
      paddingVertical:10,
      borderRadius:8,
      gap:10,
      elevation:2
    },
    watingTimeContainerTitle:{
      fontFamily:Fonts.semi_bold,
      fontSize:18
    },
    StopwatingTimeBtn:{
      marginVertical:10,
      backgroundColor:Colors.black,
      paddingVertical:8,
      borderRadius:8,
      alignItems:'center',
      paddingHorizontal:20
    },
    StopwatingTimeBtnText:{
      color:Colors.white,
      fontFamily:Fonts.regular,
      fontSize:14
    },
    pickUpLocationContainer:{
      width:'90%',
      alignSelf:'center',
      marginVertical:10,
      alignItems:'center',
      backgroundColor:Colors.grey_light,
      paddingVertical:10,
      borderRadius:8,
      alignItems:'center',
      elevation:2,
      gap:10
    },
    pickUpLocationTxt:{
      fontFamily:Fonts.regular,
      fontSize:18,
      color:Colors.black
    },
    pickUpLocationBtnContainer:{
      flexDirection:'row',
      justifyContent:'space-between',
      gap:10,
    },
    navigationIconContainerTxt:{
      fontFamily:Fonts.regular,
      fontSize:14,
      color:Colors.white,
      gap:10,
    },
    navigationIconContainer: {
      minWidth: '50%',
      backgroundColor: '#0080ff',
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginVertical:10,
      borderWidth: 1,
      borderColor: Colors.white,
      gap:10,
      zIndex: 999,
      height: 40,
      flexDirection: 'row',
    },
    chooseNavModeTxtHeader:{
      fontFamily:Fonts.regular,
      fontSize:18,
      color:Colors.black,
      marginBottom:10,
    },
    chooseNavModeTxt:{
      fontFamily:Fonts.regular,
      fontSize:14,
      color:Colors.black,
    },
    chooseNavModeContainer:{
      flexDirection:'row',
      justifyContent:'space-between',
      gap:10,
    },
    chooseNavModeItem:{
      backgroundColor:Colors.grey_light,
      padding:10,
      borderRadius:8,
      alignItems:'center',
      justifyContent:'center',
      height:40,
      marginVertical:20,
    },
    goHomeBtn:{
      backgroundColor:Colors.periwinkle,
      padding:10,
      borderRadius:8,
      alignItems:'center',
      justifyContent:'center',
      alignSelf:'center',
      marginVertical:10,
    },
goHomeBtnTxt:{
  fontFamily:Fonts.regular,
  fontSize:16,
  color:Colors.white,
},
});
